### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by ghost** [SwissBorg/lithium#75]
Hi,

What's the current status of this project? Do you have a rough roadmap or are the features stable at this point? Do you know of anybody using this in production? If so, do you know of multiple groups using this in production?

**Comment by nremond** [comment]
Hello, 

The project is used at SwissBorg in production and a couple of Swiss start-ups have expressed strong interest in this project, don't know if they are in production yet or not. 

Anyhow, yes, all major features have been implemented and are stable now.
